import type { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";
import "./globals.css";

//Pages 
import Header from "@/components/Header";
import Footer from "@/components/footer";
import Home from "./page";


const robotoCondensed = Roboto_Condensed({
  variable: "--font-robot-condensed",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${robotoCondensed.variable} antialiased`}
      >
        <Header/>
          {children}
        <Footer/>
      </body>
    </html>
  );
}
